name: CI/CD On Push To Main

on:
  push:
    branches:
      - "main"

jobs:
  test-on-ubuntu:

    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn test
      env:
        CI: true
    - run: yarn run report-coverage

    # Create key here https://codecov.io
    # Add CODECOV_TOKEN to Github Secret: 
    # https://github.com/${organization}/${repository}/settings/secrets
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.lcov
        fail_ci_if_error: true

  bump-version:
    name: "Bump Version on main"
    runs-on: ubuntu-latest
    needs: test-on-ubuntu

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
          minor-wording:  'FEATURE'
          major-wording:  'MAJOR-VERSION'
      - name: "cat package.json"
        run: cat ./package.json

  # Generate NPM_TOKEN: https://www.npmjs.com/settings/erichosick/tokens
  # Add NPM_TOKEN to Github Secret here: https://github.com/${organization}/${repository}/settings/secrets
  deploy-npmjs:
    name: "Deploy to npmjs"
    runs-on: ubuntu-latest
    needs: bump-version

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - name: "Build dist directory"
        run: yarn build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
